# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oneMultinomCalt <- function(probs) {
    .Call('_EBMAforecast_oneMultinomCalt', PACKAGE = 'EBMAforecast', probs)
}

getRGamma <- function(shape) {
    .Call('_EBMAforecast_getRGamma', PACKAGE = 'EBMAforecast', shape)
}

isNA <- function(x) {
    .Call('_EBMAforecast_isNA', PACKAGE = 'EBMAforecast', x)
}

emNorm <- function(outcome, prediction, RSQ, W, tol, maxIter, wisdom, sigma2) {
    .Call('_EBMAforecast_emNorm', PACKAGE = 'EBMAforecast', outcome, prediction, RSQ, W, tol, maxIter, wisdom, sigma2)
}

GibbsNormal <- function(outcome, prediction, W, alpha, sigma, iterations, burnin, thin) {
    .Call('_EBMAforecast_GibbsNormal', PACKAGE = 'EBMAforecast', outcome, prediction, W, alpha, sigma, iterations, burnin, thin)
}

GibbsNormalMissing <- function(outcome, prediction, W, alpha, sigma, iterations, burnin, thin) {
    .Call('_EBMAforecast_GibbsNormalMissing', PACKAGE = 'EBMAforecast', outcome, prediction, W, alpha, sigma, iterations, burnin, thin)
}

emLogit <- function(outcome, prediction, W, tol, maxIter, wisdom) {
    .Call('_EBMAforecast_emLogit', PACKAGE = 'EBMAforecast', outcome, prediction, W, tol, maxIter, wisdom)
}

GibbsLogit <- function(outcome, prediction, W, iterations, burnin, thin) {
    .Call('_EBMAforecast_GibbsLogit', PACKAGE = 'EBMAforecast', outcome, prediction, W, iterations, burnin, thin)
}

